// src/lib/streets-sector1.ts
// Nomenclator străzi Sectorul 1 București
// Sursă: date publice disponibile

export const STREETS_SECTOR1: string[] = [
  "Aleea Alexandru",
  "Aleea Circului",
  "Aleea Dealul Mitropoliei",
  "Aleea Modrogan",
  "Aleea Privighetorilor",
  "Aleea Teișani",
  "Bulevardul Aviatorilor",
  "Bulevardul Băneasa",
  "Bulevardul Brătianu Ion C.",
  "Bulevardul Dacia",
  "Bulevardul Eroilor",
  "Bulevardul Ficusului",
  "Bulevardul Lascăr Catargiu",
  "Bulevardul Magheru",
  "Bulevardul Mărăști",
  "Bulevardul Nicolae Titulescu",
  "Bulevardul Primăverii",
  "Bulevardul Titulescu Nicolae",
  "Calea Dorobanților",
  "Calea Floreasca",
  "Calea Griviței",
  "Calea Victoriei",
  "Intrarea Alexandru Donici",
  "Intrarea Arieșul",
  "Piața Aviatorilor",
  "Piața Charles de Gaulle",
  "Piața Lahovari",
  "Piața Romană",
  "Piața Victoriei",
  "Splaiurile Independenței",
  "Strada Abrud",
  "Strada Academiei",
  "Strada Acvila",
  "Strada Albac",
  "Strada Albăstricele",
  "Strada Alecu Russo",
  "Strada Alexandru Donici",
  "Strada Alexandru Philippide",
  "Strada Alexandru Sahia",
  "Strada Amiral Bălescu",
  "Strada Amiral Constantin Bălescu",
  "Strada Ana Davila",
  "Strada Andrei Mureșanu",
  "Strada Apolodor",
  "Strada Apusului",
  "Strada Argeș",
  "Strada Arh. Ion Mincu",
  "Strada Armenească",
  "Strada Avram Iancu",
  "Strada Băbeanu",
  "Strada Băiuț",
  "Strada Băneasa",
  "Strada Barbu Văcărescu",
  "Strada Batiștei",
  "Strada Berzei",
  "Strada Bicaz",
  "Strada Bistrița",
  "Strada Bogdan Petriceicu Hașdeu",
  "Strada Borșa",
  "Strada Brândușelor",
  "Strada Brezoianu Ion",
  "Strada Bruckentha",
  "Strada Bucegi",
  "Strada București-Ploiești",
  "Strada Budișteanu Constantin",
  "Strada Buiucani",
  "Strada Buzești",
  "Strada Caimatei",
  "Strada Câmpineanu Ion",
  "Strada Caporal Preda",
  "Strada Carol Davila",
  "Strada Carol Knappe",
  "Strada Castelului",
  "Strada Cazărmii",
  "Strada Căderea Bastiliei",
  "Strada Câmpul cu Narcise",
  "Strada Clucerului",
  "Strada Cobălcescu Grigore",
  "Strada Coacăzelor",
  "Strada Codrului",
  "Strada Cometei",
  "Strada Cometa",
  "Strada Constantin Aricescu",
  "Strada Constantin Cantacuzino",
  "Strada Constantin Mille",
  "Strada Constantin Noica",
  "Strada Constantin Rădulescu-Motru",
  "Strada Costache Negri",
  "Strada Cozia",
  "Strada Cristian Tell",
  "Strada Cronicar Mustea",
  "Strada Dacia",
  "Strada Dâmbovița",
  "Strada Dănilă Prepeleac",
  "Strada Dem Dobrescu",
  "Strada Dem I. Dobrescu",
  "Strada Democrației",
  "Strada Dionisie Lupu",
  "Strada Diplomat",
  "Strada Dogarilor",
  "Strada Domniței",
  "Strada Dr. Burghelea",
  "Strada Dr. Cantacuzino",
  "Strada Dr. Félix",
  "Strada Dr. Grigore Mora",
  "Strada Dr. Lister",
  "Strada Dr. Nicolae Minovici",
  "Strada Dr. Staicovici",
  "Strada Dreptății",
  "Strada Dumbrava Roșie",
  "Strada Ecaterina Teodoroiu",
  "Strada Eforie",
  "Strada Eforiei",
  "Strada Elena Văcărescu",
  "Strada Eliade Pompieru",
  "Strada Emanoil Porumbaru",
  "Strada Emil Gârleanu",
  "Strada Emil Racoviță",
  "Strada Episcopiei",
  "Strada Eroilor Sanitari",
  "Strada Eugeniu Carada",
  "Strada Fabricii",
  "Strada Fântânilor",
  "Strada Flămânda",
  "Strada Florilor",
  "Strada Frumoasă",
  "Strada Fundeni",
  "Strada G-ral Budișteanu",
  "Strada G-ral Eremia Grigorescu",
  "Strada G-ral Gheorghe Manu",
  "Strada G-ral Henri Mathias Berthelot",
  "Strada G-ral Praporgescu",
  "Strada G-ral Radu R. Rosetti",
  "Strada G-ral Ștefan Fălcoianu",
  "Strada G-ral Traian Moșoiu",
  "Strada Garlei",
  "Strada Gavril Muzicescu",
  "Strada Gelu",
  "Strada George Călinescu",
  "Strada George Enescu",
  "Strada George Georgescu",
  "Strada George Toparceanu",
  "Strada Gheorghe Asachi",
  "Strada Gheorghe Lazăr",
  "Strada Gheorghe Polizu",
  "Strada Gheorghe Vrânceanu",
  "Strada Grigore Alexandrescu",
  "Strada Grigore Cobălcescu",
  "Strada Grivița",
  "Strada Haga",
  "Strada Henri Coandă",
  "Strada Herăstrău",
  "Strada Horea",
  "Strada Iacob Andrei",
  "Strada Iacob Felix",
  "Strada Iancu de Hunedoara",
  "Strada Icoanei",
  "Strada Ienăchiță Văcărescu",
  "Strada Ierbarilor",
  "Strada Ifov",
  "Strada Inginer Zablovschi",
  "Strada Ion Câmpineanu",
  "Strada Ion Câmpinenu",
  "Strada Ion Creangă",
  "Strada Ion Georgescu",
  "Strada Ion Ghica",
  "Strada Ion Heliade Rădulescu",
  "Strada Ion Lahovari",
  "Strada Ion Minulescu",
  "Strada Ion Nistor",
  "Strada Ion Racotă",
  "Strada Ion Rațiu",
  "Strada Ion Slătineanu",
  "Strada Ion Văcărescu",
  "Strada Ionel Perlea",
  "Strada Ioniță Câmpineanu",
  "Strada Ipolit Strâmbu",
  "Strada Isvor",
  "Strada Izbiceni",
  "Strada Jean Louis Calderon",
  "Strada Jean Monnet",
  "Strada Jules Michelet",
  "Strada Justinian",
  "Strada L. Pasteur",
  "Strada Laboratorului",
  "Strada Lacul Tei",
  "Strada Lanului",
  "Strada Latino-Americană",
  "Strada Lânăriei",
  "Strada Lemnea",
  "Strada Lev Tolstoi",
  "Strada Lexandru",
  "Strada Lizeanu",
  "Strada Londra",
  "Strada Luchian Stefan",
  "Strada Lucreția Pătrășcanu",
  "Strada Luterană",
  "Strada Maica Domnului",
  "Strada Maior Coravu",
  "Strada Mamulari",
  "Strada Manea Brutaru",
  "Strada Mântuleasa",
  "Strada Mărășești",
  "Strada Maria Rosetti",
  "Strada Matei Basarab",
  "Strada Matei Millo",
  "Strada Mehadia",
  "Strada Mendeleev",
  "Strada Mercur",
  "Strada Mihai Eminescu",
  "Strada Mihail Kogălniceanu",
  "Strada Mihail Moxa",
  "Strada Mihalache Ion",
  "Strada Militari",
  "Strada Minervei",
  "Strada Mircea Vulcănescu",
  "Strada Mitropolit Dosoftei",
  "Strada Mitropoliei",
  "Strada Moise Nicoară",
  "Strada Molière",
  "Strada Monetăriei",
  "Strada Moș Ajun",
  "Strada Mozart",
  "Strada Muntele Mic",
  "Strada Murelor",
  "Strada Muzeul Zambaccian",
  "Strada Nalbei",
  "Strada Neatârnării",
  "Strada Negru Vodă",
  "Strada Nicolae Filipescu",
  "Strada Nicolae Golescu",
  "Strada Nicolae Iorga",
  "Strada Nicolae Orghidan",
  "Strada Nicolae Tonitza",
  "Strada Nikos Beloiannis",
  "Strada Nisipuri",
  "Strada Nufărului",
  "Strada Occidentului",
  "Strada Oituz",
  "Strada Oltarului",
  "Strada Olteni",
  "Strada Oneșți",
  "Strada Orhideelor",
  "Strada Ostașilor",
  "Strada Pache Protopopescu",
  "Strada Pajurei",
  "Strada Paris",
  "Strada Pârâului",
  "Strada Pericle Papahagi",
  "Strada Petru Maior",
  "Strada Petru Rareș",
  "Strada Pictor Aman",
  "Strada Pictor Arthur Verona",
  "Strada Pictor Ion Andreescu",
  "Strada Pictor Luchian",
  "Strada Pictor Rosenthal",
  "Strada Pictor Stahi",
  "Strada Pictor Verona",
  "Strada Plantelor",
  "Strada Plevnei",
  "Strada Plugarilor",
  "Strada Poet Alexe Mateevici",
  "Strada Polona",
  "Strada Polonia",
  "Strada Pompiliu Eliade",
  "Strada Principatele Unite",
  "Strada Prof. Dr. Dimitrie Gerota",
  "Strada Prof. Dr. Georgescu Urbeanu",
  "Strada Pugna",
  "Strada Pușkin Alexandru",
  "Strada Râmnicu Sărat",
  "Strada Radu de la Afumați",
  "Strada Radu Vodă",
  "Strada Rasova",
  "Strada Răducanu",
  "Strada Râmnicu Vâlcea",
  "Strada Remus Opreanu",
  "Strada Republicii",
  "Strada Rezistanței",
  "Strada Ritmului",
  "Strada Romană",
  "Strada Romulus Vuia",
  "Strada Rosetti Constantin A.",
  "Strada Rozelor",
  "Strada Sandu Aldea",
  "Strada Sanoviței",
  "Strada Sărindar",
  "Strada Scaune",
  "Strada Schitu Darvari",
  "Strada Serg. Ionel Nițu",
  "Strada Sergent Nițu Ionel",
  "Strada Sf. Constantin",
  "Strada Sf. Elefterie",
  "Strada Sf. Gheorge Nou",
  "Strada Sf. Ion Nou",
  "Strada Sf. Ștefan",
  "Strada Sf. Vineri",
  "Strada Sibiu",
  "Strada Silistra",
  "Strada Simion Bărnuțiu",
  "Strada Smârdan",
  "Strada Snagov",
  "Strada Sofianu Nae",
  "Strada Sorin Ionescu",
  "Strada Speranței",
  "Strada Spiru Haret",
  "Strada Știrbei Vodă",
  "Strada Sturdza Mihai",
  "Strada Suceava",
  "Strada Tache Ionescu",
  "Strada Teleajen",
  "Strada Telița",
  "Strada Teodor Ștefănescu",
  "Strada Timișoara",
  "Strada Titulescu Nicolae",
  "Strada Toamnei",
  "Strada Traian",
  "Strada Traian Demetrescu",
  "Strada Tudor Arghezi",
  "Strada Tudor Ștefan",
  "Strada Tunari",
  "Strada Turda",
  "Strada Turnu Măgurele",
  "Strada Turturedelor",
  "Strada Unirii",
  "Strada Universității",
  "Strada Uranus",
  "Strada Urdăreanu",
  "Strada Urlătoarei",
  "Strada Uzinei",
  "Strada Vadu Izei",
  "Strada Văcărescu Barbu",
  "Strada Vânători",
  "Strada Vârful cu Dor",
  "Strada Vasile Alecsandri",
  "Strada Vasile Lascăr",
  "Strada Vasile Pârvan",
  "Strada Vasile Roaită",
  "Strada Vasile Toroțeanu",
  "Strada Venerei",
  "Strada Veronica Micle",
  "Strada Victor Eftimiu",
  "Strada Visarion",
  "Strada Viței",
  "Strada Vlad Județ",
  "Strada Vladimirescu Tudor",
  "Strada Vlăsiei",
  "Strada Washington",
  "Strada Winnipeg",
  "Strada Xenofon",
  "Strada Ziduri Moși",
  "Șos. Băneasa",
  "Șos. Colentina",
  "Șos. Kiseleff",
  "Șos. Nordului",
  "Șos. Pavel Kiseleff",
  "Șos. Pipera",
  "Șoseaua Aviatorilor",
  "Șoseaua Băneasa",
  "Șoseaua București-Ploiești",
  "Șoseaua Chitilei",
  "Șoseaua Colentina",
  "Șoseaua Fabrica de Glucoză",
  "Șoseaua Floreasca",
  "Șoseaua Giurgiului",
  "Șoseaua Kiseleff",
  "Șoseaua Nordului",
  "Șoseaua Pantelimon",
  "Șoseaua Pipera",
  "Șoseaua Sălăjan",
  "Șoseaua Ștefan cel Mare",
  "Șoseaua Vergului",
].sort();

export function searchStreets(query: string, limit = 8): string[] {
  if (!query || query.length < 2) return [];
  const q = query.toLowerCase().trim();
  return STREETS_SECTOR1
    .filter(s => s.toLowerCase().includes(q))
    .slice(0, limit);
}
